// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbFlMIj8BcZEQGycPl0aYQoBD6FDbgaZM',
    appId: '1:584626996904:web:3ff257ab18990a486fa49d',
    messagingSenderId: '584626996904',
    projectId: 'figureitout-d4721',
    authDomain: 'figureitout-d4721.firebaseapp.com',
    databaseURL: 'https://figureitout-d4721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'figureitout-d4721.appspot.com',
    measurementId: 'G-5VR9237HR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxpRAXpD9j-AndLywaoDjBY-DOIc23Vk',
    appId: '1:584626996904:android:23bd16f64bae5ee76fa49d',
    messagingSenderId: '584626996904',
    projectId: 'figureitout-d4721',
    databaseURL: 'https://figureitout-d4721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'figureitout-d4721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyhqQPEUwz3riAGKxihmM2BR01X8x1ok8',
    appId: '1:584626996904:ios:6d2617435d5de34a6fa49d',
    messagingSenderId: '584626996904',
    projectId: 'figureitout-d4721',
    databaseURL: 'https://figureitout-d4721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'figureitout-d4721.appspot.com',
    iosBundleId: 'com.yourdomain.figurenew2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyhqQPEUwz3riAGKxihmM2BR01X8x1ok8',
    appId: '1:584626996904:ios:6d2617435d5de34a6fa49d',
    messagingSenderId: '584626996904',
    projectId: 'figureitout-d4721',
    databaseURL: 'https://figureitout-d4721-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'figureitout-d4721.appspot.com',
    iosBundleId: 'com.yourdomain.figurenew2',
  );
}
