// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdMzTyoHt0vslFOwhevKWSK1dgZlRWTVw',
    appId: '1:139588718126:web:a02af226334090305719bf',
    messagingSenderId: '139588718126',
    projectId: 'new-figure-it-out-login',
    authDomain: 'new-figure-it-out-login.firebaseapp.com',
    storageBucket: 'new-figure-it-out-login.appspot.com',
    measurementId: 'G-MRZ3D53L3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHC6i0eaM8eXc1KRd4dUvua-uXSv_Ml2M',
    appId: '1:139588718126:android:db234316318953e95719bf',
    messagingSenderId: '139588718126',
    projectId: 'new-figure-it-out-login',
    storageBucket: 'new-figure-it-out-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARTCiTPXA2YvuzunJo1StLIJNQZTW7Mh8',
    appId: '1:139588718126:ios:dc23012ea413a2185719bf',
    messagingSenderId: '139588718126',
    projectId: 'new-figure-it-out-login',
    storageBucket: 'new-figure-it-out-login.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARTCiTPXA2YvuzunJo1StLIJNQZTW7Mh8',
    appId: '1:139588718126:ios:184696ba6e1d39505719bf',
    messagingSenderId: '139588718126',
    projectId: 'new-figure-it-out-login',
    storageBucket: 'new-figure-it-out-login.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
